volumes:
  -.:/app
ports:
  - "3000:3000"
environment:
  - NODE_ENV: development
  - DB_HOST: database
  - DB_PORT: 3306
  - DB_USER: techstore_app
  - DB_PASSWORD: ***REDACTED***
  - DB_NAME: techstore


database:
  image: mysql:8.0
  environment:
    - MYSQL_ROOT_PASSWORD: ***REDACTED***
    - MYSQL_DATABASE: techstore
    - MYSQL_USER: techstore_app
    - MYSQL_PASSWORD: ***REDACTED***
    - MYSQL_ROOT_PASSWORD: Root***REDACTED***
  ports:
    - "3306:3306"